spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/animal_care?serverTimezone=UTC
    username: root
    password: skqldi12
  sql:
    init:
      encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create