spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animal_care
    username: root
    password: 12345678
    driver: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update