server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/animal_care?serverTimezone=UTC
    username: animalcare
    password: animalcare123
    driver: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌

logging.level:
  org.hibernate.SQL: debug
  
  # 타임리프 실시간 반영
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false