spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/animal_care?serverTimezone=UTC
    username: root
    password: root123
    driver: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8